# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
# source 'https://github.com/CocoaPods/Specs.git'

target 'RTCSolution' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   use_frameworks!

  pod 'RTCCommon', :path => 'RTCCommon'
  
  pod 'RTCCommonView', :path => 'RTCCommonView'

  pod 'RTCBeaconTower', :path => 'RTCBeaconTower'
  
#end

 pod 'AliRTCSdk',        :path => 'AliRtcSDK_iOS'
 pod 'AFNetworking',     :git => 'https://github.com/AFNetworking/AFNetworking.git',  :tag=>'4.0.1'

 
end
